version: "1.0"
services:
  server:
    image: ghcr.io/andregcx/ast-teamcity-docker:latest
    ports:
      - "8111:8111"
    volumes:
      - ./teamcity-server/data:C:/ProgramData/JetBrains/TeamCity
      - ./teamcity-server/logs:C:/TeamCity/logs
    mem_limit: 2g
  agent:
    image: jetbrains/teamcity-agent:latest
    environment:
      - SERVER_URL=http://localhost:8111
      - TEAMCITY_SERVER_MEM_OPTS=-Xmx2g -XX:ReservedCodeCacheSize=350m
